;системы
[System]
pole=16
param1=dos
param2=Windows
param3=Linux
param4=Unix
param5=IOS
param6=Mac
param7=Sony Plastation
param8=Sony Plastation Portabel
param9=Sony Plastation 2
param10=Sony Plastation 3
param11=Алгоритмы
param12=Администратирование
param13=SDK
param14=ЛВС
param15=Справочники
param16=Другая

; язык написаной книги
[Lang]
pole=2
param1=Русский
param2=Англиский

; где нужно работать
[Studio]
pole=5
param1=MVS
param2=BORLOND
param3=QT
param4=CLEAN
param5=Другая

; файловый формат
[Format]
pole=8
param1=.doc
param2=.pdf
param3=.djvu
param4=.fb2
param5=.epub
param6=.html
param7=.chm
param8=.txt

;темы блоки описание
[Tema]
pole=15
param1=dos
param2=OpenGl
param3=DirectX
param4=Windows
param5=Linux
param6=SDK
param7=Администратор
param8=Базы данных
param9=Администратирование ЛВС
param10=CISCO
param11=Huawei
param12=Juniper
param13=Статья
param14=Справочник 
param15=Другое

;
[Tipog]
pole=4
param1=печатное
param2=электронное
param3=купить
param4=электронное и печатное

;
[Application]
pole=4
param1=Нет
param2=Есть
param3=Искать
param4=Версия старая



;настройка ситемы текст и окна
[Fonts]
memo=25
list1=8
list2=8
list3=8
text=8
xsize=0
ysize=0
fullscreen=1

;формат для opendiolog
[files]
file1=Все форматы|*.*|Все подерживающие форматы|*.doc;*.docx;*.html;*.chm;*.htm;*.mth;*.chm;*.pdf;*.djvu;*.djv;*.fb2;*.epub;*.txt;*.rar;*.zip;*.7z;|Текстовый формат|*.doc;*.docx;*.txt|Дежавю Формат|*.djvu;*.djv|Adobe Acrobat pdf|*.pdf|Электронный книги|*.fb2;*.epub|Интернет Формат|*.html;*.chm;*.htm;*.mth;

file2=Все подерживающие форматы|*.*|Jpg|*.jpg;*.docx|pdf|*.pdf 


;путь к файлу
[part]
param1=E:\Book
